import { Orbitron } from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({
	subsets: ["latin"],
	weight: "400",
	variable: "--font-orbitron",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} antialiased`}
      >
        <div className="main-bg absolute top-0 left-0 w-full -z-10"></div>
        {children}
      </body>
    </html>
  );
}
